CREATE TABLE TBL_PRODUCTO(
                             PRODUCTO_ID NUMERIC(6) NOT NULL PRIMARY KEY,
                             NOMBRE VARCHAR2(240)NOT NULL UNIQUE,
                             DESCRIPCION VARCHAR2(240) NOT NULL,
                             STOCK_MINIMO NUMERIC(4,0) NOT NULL,
                             STOCK_MAXIMO NUMERIC(8,0) NOT NULL,
                             PRECIO NUMERIC(6,2) NOT NULL,
                             FECHA_VENCIMIENTO DATE NULL,
                             ESTADO CHAR(1)DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCTO;

INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,DESCRIPCION,STOCK_MINIMO,STOCK_MAXIMO,PRECIO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Lenovo Y700','Lenovo ideapad Y700,16 ram, DDR4 memory',5,100,7500.0);

COMMIT;

CREATE TABLE TBL_CLIENTE(
                            CLIENTE_ID NUMERIC(6) NOT NULL PRIMARY KEY,
                            RAZON_SOCIAL VARCHAR2(240)NOT NULL UNIQUE,
                            RUC CHAR2(11) NOT NULL UNIQUE,
                            CORREO VARCHAR2(60) NOT NULL,
                            DIRECCION VARCHAR2(400) NOT NULL,
                            TELEFONO VARCHAR2(20) NOT NULL,
                            ESTADO CHAR(1)DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_CLIENTE;

INSERT INTO TBL_CLIENTE(CLIENTE_ID,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'CLARO EMRPESAS','10751193811','AV LARCO 520','442-1210','ANTHONY@GMAIL.COM');

INSERT INTO TBL_CLIENTE(CLIENTE_ID,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MOVISTAR EMRPESAS','20751193822','AV LARCO 238','442-4620','ANTHONY09@GMAIL.COM');

COMMIT;